insert into posts (title, author, content, created_time, modified_time) values ('테스트4', 'test4@gmail.com', '테스트4의 본문', now(), now());
insert into posts (title, author, content, created_time, modified_time) values ('테스트1', 'test1@gmail.com', '테스트1의 본문', now(), now());
insert into posts (title, author, content, created_time, modified_time) values ('테스트2', 'test2@gmail.com', '테스트2의 본문', now(), now());
insert into posts (title, author, content, created_time, modified_time) values ('테스트3', 'test3@gmail.com', '테스트3의 본문', now(), now());
insert into todos (todo, created_time, modified_time, complete_yn) values ('빨래', now(), now(), 'N');
insert into todos (todo, created_time, modified_time, complete_yn) values ('설겆이', now(), now(), 'N');
insert into todos (todo, created_time, modified_time, complete_yn) values ('청소', now(), now(), 'N');
insert into todos (todo, created_time, modified_time, complete_yn) values ('방청소', now(), now(), 'N');
insert into todos (todo, created_time, modified_time, complete_yn) values ('걸레질', now(), now(), 'N');
insert into todos (todo, created_time, modified_time, complete_yn) values ('분리수거', now(), now(), 'N');
insert into todos (todo, created_time, modified_time, complete_yn) values ('음식물처리', now(), now(), 'N');
